services:
  - type: web
    name: bankingwebapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python bankapp/manage.py migrate && python bankapp/manage.py collectstatic --noinput"
    startCommand: "gunicorn bankapp.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromBuild: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    healthCheckPath: /
    staticPublicPath: /staticfiles

databases:
  - name: postgres
    plan: free
